; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f411re]
platform = ststm32
board = nucleo_f411re
framework = stm32cube

lib_deps = 
    FreeRTOS
lib_ignore =
    eigen

build_flags =
  -mfpu=fpv4-sp-d16
  -mfloat-abi=softfp
  -DF4
  -D DEV 
  -I lib/FreeRTOS/include
  -I lib/FreeRTOS/CMSIS_RTOS_V2
  -I lib/FreeRTOS/portable/GCC/ARM_CM4F
  -Ilib/eigen
  -Iinclude

lib_archive = no
lib_ldf_mode = deep+

check_tool = clangtidy, cppcheck

check_src_filters =
    +<src/**>
    -<lib/**>
    -<.pio/**>
    -<lib/FreeRTOS/include/*>
    -<lib/FreeRTOS/CMSIS_RTOS_V2/*>
    -<lib/FreeRTOS/portable/GCC/ARM_CM4F/*>
    -<lib/eigen/*>

check_flags =
    clangtidy: --config-file=../.clang-tidy
    cppcheck: --enable=all
    cppcheck: --addon=misra
    cppcheck: --inline-suppr
    cppcheck: --suppressions-list=cppcheck.suppress
    cppcheck: --showtime=file-total 
    cppcheck: --inconclusive
    cppcheck: --force
    cppcheck: src lib/braiteoiri/include lib/comheadan/include


[env:sil]
platform = native
test_build_src = yes

lib_extra_dirs = src
lib_ignore =
    eigen
    MPU6050
    BMP390
    braiteoiri
    comheadan

build_src_filter =
    +<src/fsm.cpp>
    +<src/tools/kalman_filter.cpp>
    +<src/tools/state_machine.cpp>
    +<src/**>
    +<test/**>
    +<lib/braiteoiri/src/IMU/IMU.cpp>      
    +<lib/braiteoiri/src/Baro/baro.cpp> 
    -<lib/braiteoiri/src/IMU/MPU6050/*>
    -<lib/braiteoiri/src/Baro/BMP390/*>
    -<lib/comheadan/src/SPI/*>
    -<lib/comheadan/src/I2C/*>
    -<lib/eigen/bench*>

lib_archive = no

build_flags = 
    -std=gnu++17
    -DUNIT_TEST
    -Ilib/eigen
    -Ilib/braiteoiri/include/
    -Ilib/comheadan/include/
    -Iinclude